// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxrhz702lPYTJVDeKDpP2xM53u8z1C0aA',
    appId: '1:74080605509:web:972e5806e9788be75c5a2c',
    messagingSenderId: '74080605509',
    projectId: 'db-tum',
    authDomain: 'db-tum.firebaseapp.com',
    storageBucket: 'db-tum.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUDdElL34gEN2UsZk5liJNhv1ts769riE',
    appId: '1:74080605509:android:4ea676fcf3b6813e5c5a2c',
    messagingSenderId: '74080605509',
    projectId: 'db-tum',
    storageBucket: 'db-tum.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnttLV_U7S06Kb0nSQjb6ms_hmvotRus4',
    appId: '1:74080605509:ios:717f4aed1dadb3705c5a2c',
    messagingSenderId: '74080605509',
    projectId: 'db-tum',
    storageBucket: 'db-tum.firebasestorage.app',
    iosBundleId: 'com.example.tumBeta',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnttLV_U7S06Kb0nSQjb6ms_hmvotRus4',
    appId: '1:74080605509:ios:717f4aed1dadb3705c5a2c',
    messagingSenderId: '74080605509',
    projectId: 'db-tum',
    storageBucket: 'db-tum.firebasestorage.app',
    iosBundleId: 'com.example.tumBeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxrhz702lPYTJVDeKDpP2xM53u8z1C0aA',
    appId: '1:74080605509:web:031c3ae6ba1205145c5a2c',
    messagingSenderId: '74080605509',
    projectId: 'db-tum',
    authDomain: 'db-tum.firebaseapp.com',
    storageBucket: 'db-tum.firebasestorage.app',
  );
}
